# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papertrail', '0002_auto_20160125_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryrelatedobject',
            name='related_id',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
